--------------------------------------------------------
-- Archivo creado  - lunes-noviembre-15-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CLIENTE
--------------------------------------------------------

  CREATE TABLE "CLIENTE" 
   (	"ID_CLIENTE" NUMBER(10,0), 
	"NOMBRE" VARCHAR2(200 BYTE), 
	"MAIL" VARCHAR2(200 BYTE), 
	"FEC_NACIMIENTO" DATE, 
	"ID_COMUNA" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table COMUNA
--------------------------------------------------------

  CREATE TABLE "COMUNA" 
   (	"ID_COMUNA" NUMBER(10,0), 
	"NOMBRE_COMUNA" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USUARIO
--------------------------------------------------------

  CREATE TABLE "USUARIO" 
   (	"USU_ID" NUMBER(10,0), 
	"LOGIN" VARCHAR2(255 BYTE), 
	"PASS" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into CLIENTE
SET DEFINE OFF;
Insert into CLIENTE (ID_CLIENTE,NOMBRE,MAIL,FEC_NACIMIENTO,ID_COMUNA) values ('1','Juan Nieve','jnieve@mail.com',to_date('17/11/87','DD/MM/RR'),'2');
Insert into CLIENTE (ID_CLIENTE,NOMBRE,MAIL,FEC_NACIMIENTO,ID_COMUNA) values ('2','Ana Molina','amolina@mail.com',to_date('17/05/89','DD/MM/RR'),'6');
Insert into CLIENTE (ID_CLIENTE,NOMBRE,MAIL,FEC_NACIMIENTO,ID_COMUNA) values ('3','Andrés Perez','aperez@mail.com',to_date('13/06/90','DD/MM/RR'),'3');
Insert into CLIENTE (ID_CLIENTE,NOMBRE,MAIL,FEC_NACIMIENTO,ID_COMUNA) values ('4','juan','jaun@mail.com',to_date('12/10/80','DD/MM/RR'),'6');
REM INSERTING into COMUNA
SET DEFINE OFF;
Insert into COMUNA (ID_COMUNA,NOMBRE_COMUNA) values ('1','MAIPU');
Insert into COMUNA (ID_COMUNA,NOMBRE_COMUNA) values ('2','PUENTE ALTO');
Insert into COMUNA (ID_COMUNA,NOMBRE_COMUNA) values ('3','RENCA');
Insert into COMUNA (ID_COMUNA,NOMBRE_COMUNA) values ('4','QUILICURA');
Insert into COMUNA (ID_COMUNA,NOMBRE_COMUNA) values ('5','PROVIDENCIA|');
Insert into COMUNA (ID_COMUNA,NOMBRE_COMUNA) values ('6','NUNOA');
Insert into COMUNA (ID_COMUNA,NOMBRE_COMUNA) values ('7','RECOLETA');
Insert into COMUNA (ID_COMUNA,NOMBRE_COMUNA) values ('8','SAN MIGUEL');
Insert into COMUNA (ID_COMUNA,NOMBRE_COMUNA) values ('9','MACUL');
Insert into COMUNA (ID_COMUNA,NOMBRE_COMUNA) values ('10','PUDAHUEL');
REM INSERTING into USUARIO
SET DEFINE OFF;
Insert into USUARIO (USU_ID,LOGIN,PASS) values ('1','admin','123456');
--------------------------------------------------------
--  DDL for Index PK_USUARIO
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_USUARIO" ON "USUARIO" ("USU_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table USUARIO
--------------------------------------------------------

  ALTER TABLE "USUARIO" ADD CONSTRAINT "PK_USUARIO" PRIMARY KEY ("USU_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COMUNA
--------------------------------------------------------

  ALTER TABLE "COMUNA" ADD PRIMARY KEY ("ID_COMUNA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CLIENTE
--------------------------------------------------------

  ALTER TABLE "CLIENTE" ADD CONSTRAINT "FK_CLIENTE_COMUNA" FOREIGN KEY ("ID_COMUNA")
	  REFERENCES "COMUNA" ("ID_COMUNA") ENABLE;
